name: Fetch Merge Commit SHAs of Open PRs

on:
  workflow_dispatch:  # Allows manual triggering of workflow

jobs:
  fetch-pr-merge-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch PRs information
        id: fetch-prs
        run: |
          PAGE=1
          PRS=()

          while true; do
            response=$(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open&page=$PAGE")
            page_prs=$(echo "$response" | jq -r '.[].merge_commit_sha')

            # Break loop if no more PRs or empty response
            if [ -z "$page_prs" ]; then
              break
            fi

            # Add PRs from this page to the PRS array
            PRS+=("$page_prs")

            PAGE=$((PAGE + 1))
          done

          echo "::set-output name=prs::$(echo "${PRS[@]}")"

      - name: Output PRs array
        run: |
          echo "Merge commit SHAs of open PRs:"
          for pr in "${{ steps.fetch-prs.outputs.prs }}"; do
            echo "- $pr"
          done
