name: Trigger Workflow in RepoB

on:
  push:
    branches:
      - main  # Or any branch you prefer triggering this workflow from

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in RepoB
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/anusreelakshmi/Repo-B/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
