name: CI

on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch all open PRs
      id: fetch-prs
      run: |
        PR_SHAS=()
        for pr_number in $(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" | jq -r '.[].number'); do
          pr_sha=$(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls/$pr_number" | jq -r '.merge_commit_sha')
          PR_SHAS+=("$pr_sha")
        done
        echo "PR_SHAS=(${PR_SHAS[@]})" >> $GITHUB_ENV

    - name: Set up matrix
      id: set-matrix
      run: |
        matrix=$(printf '{"include": ['; for sha in "${PR_SHAS[@]}"; do printf '{"sha": "%s"},' "$sha"; done | sed 's/,$//'; printf '] }')
        echo "::set-output name=matrix::$matrix"

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}

    - name: Run tests
      run: |
        echo "Running tests for SHA: ${{ matrix.sha }}"
        # Add your test commands here
