name: Build

on:
  push:


jobs:
  get-prs:
    runs-on: ubuntu-latest
    outputs:
      pr_info: ${{ steps.get-prs.outputs.pr_info }}
    steps:
      - name: Fetch open PRs
        id: get-prs
        run: |
          PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/OpenLiberty/liberty-tools-intellij/pulls?state=open&sort=created&direction=desc&per_page=100" \
                    | jq -r '.[] | "\(.number) \(.merge_commit_sha)"')

          echo "::set-output name=pr_info::$PR_INFO"

  run-job-per-pr:
    needs: get-prs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr_info: ${{ needs.get-prs.outputs.pr_info }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run job for each PR
        run: |
          # Extract PR number and merge commit SHA from the pr_info string
          PR_NUMBER=$(echo "${{ matrix.pr_info }}" | awk '{print $1}')
          MERGE_COMMIT_SHA=$(echo "${{ matrix.pr_info }}" | awk '{print $2}')

          echo "Running job for PR $PR_NUMBER with merge commit SHA $MERGE_COMMIT_SHA"

          # Perform actions specific to each PR, using $MERGE_COMMIT_SHA as needed
          # Replace the following echo with your actual job commands
          echo "Example command using merge commit SHA: git show $MERGE_COMMIT_SHA"

