name: Fetch PR Merge SHAs

on:
  push:
  

jobs:
  fetch-pr-shas:
    runs-on: ubuntu-latest
    outputs:
      pr_shas: ${{ steps.fetch-prs.outputs.pr_shas }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all open PRs
        id: fetch-prs
        run: |
          PR_SHAS=()
          for pr_number in $(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" | jq -r '.[].number'); do
            pr_sha=$(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls/$pr_number" | jq -r '.merge_commit_sha')
            PR_SHAS+=("$pr_sha")
          done
          PR_SHAS_STRING=$(printf ", %s" "${PR_SHAS[@]}")
          PR_SHAS_STRING="[${PR_SHAS_STRING:2}]"
          echo "::set-output name=pr_shas::$PR_SHAS_STRING"

  example_matrix:
    runs-on: ${{ matrix.runtime }}
    needs: fetch-pr-shas
    strategy:
      matrix:
        runtime: [ ubuntu-latest, macOS-latest, windows-latest ]
        include:
          - runtime: ubuntu-latest
            pr_shas: ${{ needs.fetch-pr-shas.outputs.pr_shas }}
          - runtime: macOS-latest
            pr_shas: ${{ needs.fetch-pr-shas.outputs.pr_shas }}
          - runtime: windows-latest
            pr_shas: ${{ needs.fetch-pr-shas.outputs.pr_shas }}
    steps:
    - name: Checkout pull request merge commits
      uses: actions/checkout@v3
      with:
        repository: redhat-developer/lsp4ij
        ref: ${{ matrix.pr_shas }}

