name: CI

on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch all open PRs
      id: fetch-prs
      run: |
        PR_SHAS=()
        for pr_number in $(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" | jq -r '.[].number'); do
          pr_sha=$(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls/$pr_number" | jq -r '.merge_commit_sha')
          PR_SHAS+=("$pr_sha")
        done
        echo "PR_SHAS=(${PR_SHAS[@]})" >> $GITHUB_ENV

    - name: Process each PR SHA
      run: |
        for sha in ${PR_SHAS[@]}; do
          echo "Processing SHA: $sha"
          # Add your processing commands here
        done


  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        merge-commit: ${{ fromJson(${PR_SHAS[@]}) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.merge-commit }}

    - name: Run tests
      run: |
        echo "Running tests for SHA: ${{ matrix.sha }}"
        # Add your test commands here
