name: Fetch Merge Commit SHAs of Open PRs

on:
  push: 

jobs:
  fetch-pr-merge-shas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Merge Commit SHAs of Open PRs
        id: fetch-shas
        uses: actions/github-script@v6
        with:
          script: |
            const prs = await github.paginate("GET /repos/{owner}/{repo}/pulls", {
              owner: "redhat-developer",
              repo: "lsp4ij",
              state: "open",
            });

            if (prs.length === 0) {
              return core.info("No open pull requests found.");
            }

            const shaList = [];
            for (const pr of prs) {
              if (pr.merge_commit_sha) {
                shaList.push({
                  number: pr.number,
                  merge_commit_sha: pr.merge_commit_sha,
                });
              }
            }

            core.setOutput("sha_list", JSON.stringify(shaList));
            core.info(`Found ${shaList.length} PR(s) with merge commit SHAs.`);
      
      - name: Print Merge Commit SHAs
        run: |
          echo "Merge commit SHAs of open PRs:"
          echo ${{ steps.fetch-shas.outputs.sha_list }}
