name: Get PR Merge SHAs

on:
  push:
  
jobs:
  get-pr-merge-shas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PRs
        id: get-prs
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open")
          echo "::set-output name=response::$response"

      - name: Extract PR merge SHAs
        id: extract-shas
        run: |
          echo "${{ steps.get-prs.outputs.response }}" \
            | jq -r '.[] | .merge_commit_sha' \
            | while read sha; do
                echo "::set-output name=shas::$sha"
              done

      - name: Display PR merge SHAs
        run: |
          echo "Merge SHAs of open PRs:"
          echo "${{ steps.extract-shas.outputs.shas }}"
