name: Fetch Merge Commit SHAs of Open PRs

on:
  push: 

jobs:
  fetch-pr-merge-shas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Merge Commit SHAs of Open PRs
        id: fetch-shas
        uses: actions/github-script@v6
        with:
          script: |
            const prs = await github.paginate("GET /repos/{owner}/{repo}/pulls", {
              owner: "redhat-developer",
              repo: "lsp4ij",
              state: "open",
            });

            if (prs.length === 0) {
              return core.info("No open pull requests found.");
            }

            const shaList = [];
            for (const pr of prs) {
              if (pr.merge_commit_sha) {
                shaList.push(pr.merge_commit_sha);
              }
            }

            core.setOutput("sha_list", shaList.join("\n"));
            core.info(`Found ${shaList.length} PR(s) with merge commit SHAs.`);

      - name: Set up Matrix
        id: setup-matrix
        run: |
          echo "::set-output name=matrix::$(echo '${{ steps.fetch-shas.outputs.sha_list }}' | jq -R 'split("\n")')"

  use-shas-in-matrix:
    needs: fetch-pr-merge-shas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sha: ${{fromJson(needs.fetch-pr-merge-shas.outputs.sha_list)}}
    steps:
      - name: Print SHA in Matrix
        run: |
          echo "Using SHA: ${{ matrix.sha }}"
