name: Build

on:
  push:
   

jobs:
  get-prs:
    runs-on: ubuntu-latest
    outputs:
      prs-sha: ${{ steps.get-prs.outputs.prs-sha }}
    steps:
      - name: Fetch open PRs
        id: get-prs
        run: |
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" \
                | jq -r '.[] | .merge_commit_sha')

          echo "::set-output name=prs-sha::$PRS"

  print-sha:
    needs: get-prs
    runs-on: ubuntu-latest
    steps:
      - name: Print PRs merge commit SHA
        run: |
          PRS_SHA="${{ needs.get-prs.outputs.prs-sha }}"

          echo "Merge commit SHA of opened PRs:"
          echo "$PRS_SHA"
