name: Generate and checkout merge SHAs

on:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          pr_merge_shas=("8b31079bfcc458794cf9de51176e47e8e86ed548" "b318be60202fe0aca86802f341e08393ea7e43d7" "6543dacb85f3bc1532e5ccfe34dfd04a5eabeaa8")
          matrix=$(printf '{"merge-commit": [%s]}' $(IFS=,; echo "${pr_merge_shas[*]/#/,\"}"))
          echo "::set-output name=matrix::$matrix"

  checkout-merge-commits:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout pull request merge commit
        uses: actions/checkout@v3
        with:
          repository: redhat-developer/lsp4ij
          ref: ${{ matrix.merge-commit }}
