name: Fetch PR Merge SHAs

on:
  push:
  

jobs:
  fetch-pr-shas:
    runs-on: ubuntu-latest
    outputs:
      pr_shas: ${{ steps.fetch-prs.outputs.pr_shas }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all open PRs
        id: fetch-prs
        run: |
          PR_SHAS=()
          for pr_number in $(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" | jq -r '.[].number'); do
            pr_sha=$(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls/$pr_number" | jq -r '.merge_commit_sha')
            PR_SHAS+=("$pr_sha")
          done
          echo "::set-output name=pr_shas::${PR_SHAS[@]}"

  checkout-pr-sha:
    runs-on: ubuntu-latest
    needs: fetch-pr-shas
    strategy:
      matrix:
        pr_sha: ${{ fromJson(needs.fetch-pr-shas.outputs.pr_shas) }}
    steps:
      - name: Checkout pull request merge commit
        uses: actions/checkout@v3
        with:
          repository: redhat-developer/lsp4ij
          ref: ${{ matrix.pr_sha }}
