name: Fetch Merge Commit SHAs and Use in Strategy Matrix

on:
  push:

jobs:
  fetch-pr-merge-shas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Merge Commit SHAs of Open PRs
        id: fetch-shas
        uses: actions/github-script@v6
        with:
          script: |
            const prs = await github.paginate("GET /repos/{owner}/{repo}/pulls", {
              owner: "redhat-developer",
              repo: "lsp4ij",
              state: "open",
            });

            if (prs.length === 0) {
              return core.info("No open pull requests found.");
            }

            const shaList = [];
            for (const pr of prs) {
              if (pr.merge_commit_sha) {
                shaList.push(pr.merge_commit_sha);
              }
            }

            core.setOutput("sha_list", shaList.join(","));
            core.info(`Found ${shaList.length} PR(s) with merge commit SHAs.`);
      
      - name: Print Merge Commit SHAs
        run: |
          echo "Merge commit SHAs of open PRs:"
          echo "${{ steps.fetch-shas.outputs.sha_list }}"

      - name: Use Merge Commit SHAs in Strategy Matrix
        id: use-in-matrix
        run: |
          echo "::set-output name=matrix::$(echo '${{ steps.fetch-shas.outputs.sha_list }}' | tr ',' '\n' | awk '{print \"  - sha: \"$1}')"
      
  example-job:
    needs: fetch-pr-merge-shas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ${{fromJson(steps.use-in-matrix.outputs.matrix)}}

    steps:
      - name: Print SHA in Job
        run: echo "SHA in this job:${{ matrix.sha }}"
