name: Build

on:
  push:


jobs:
  get-prs:
    runs-on: ubuntu-latest
    outputs:
      pr_info: ${{ steps.get-prs.outputs.pr_info }}
    steps:
      - name: Fetch open PRs
        id: get-prs
        run: |
          PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open&sort=created&direction=desc&per_page=100" \
                    | jq -r '.[] | "\(.number) \(.merge_commit_sha)"')

          echo "::set-output name=pr_info::$PR_INFO"

  print-pr-info:
    needs: get-prs
    runs-on: ubuntu-latest
    steps:
      - name: Print PRs info
        run: |
          PR_INFO="${{ needs.get-prs.outputs.pr_info }}"

          echo "Open PRs information:"
          echo "$PR_INFO"
