name: Run Dynamic Number of Jobs
on:
  push: 
  workflow_dispatch:
  
jobs:
  generate-job-strategy-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch all opened pull requests and their merge commit SHAs'
        shell: bash
        id: fetch_all_opened_pull_requests
        run: |
          pr_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" \
          | jq -r '.[] | "\(.number) \(.merge_commit_sha)"')
          
          while read -r line; do
            pr_number=$(echo "$line" | awk '{print $1}')
            pr_merge_sha=$(echo "$line" | awk '{print $2}')
            echo "$pr_number" >> pr_numbers.txt
            echo "$pr_merge_sha" >> pr_merge_shas.txt
          done <<< "$pr_info"
      
          echo "Matrix of Pull Request Numbers:"
          cat pr_numbers.txt
      
          echo "Matrix of Merge Commit SHAs:"
          cat pr_merge_shas.txt


