name: Fetch PR Merge SHAs

on:
  push:

jobs:
  fetch-pr-shas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Git credentials
        run: git config --global credential.helper store
      
      - name: Fetch all open PRs
        id: fetch-prs
        run: |
          PR_SHAS=()
          for pr_number in $(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" | jq -r '.[].number'); do
            pr_sha=$(curl -s "https://api.github.com/repos/redhat-developer/lsp4ij/pulls/$pr_number" | jq -r '.merge_commit_sha')
            PR_SHAS+=("$pr_sha")
          done
          PR_SHAS_STRING=$(printf ", %s" "${PR_SHAS[@]}")
          PR_SHAS_STRING="[${PR_SHAS_STRING:2}]"
          echo "::set-output name=pr_shas::$PR_SHAS_STRING"
        
      - name: Print PR SHAs
        run: echo "PR SHAs:${{ steps.fetch-prs.outputs.pr_shas }}"

      - name: Use PR SHAs as matrix
        id: matrix-params
        run: echo "::set-output name=matrix::$(echo '${{ steps.fetch-prs.outputs.pr_shas }}' | jq -c '.')"

  example_matrix:
    runs-on: ${{ matrix.os }}
    needs: fetch-pr-shas
    strategy:
      matrix:
        pr_sha:
          - ${{ steps.matrix-params.outputs.matrix }}
        runtime: [ linux, mac, windows ]
        include:
          - runtime: linux
            os: ubuntu-latest
          - runtime: mac
            os: macOS-latest
          - runtime: windows
            os: windows-latest
    steps:
      - name: Checkout pull request merge commits
        uses: actions/checkout@v3
        with:
          repository: redhat-developer/lsp4ij
          ref: ${{ matrix.pr_sha }}
