name: Fetch All Open Pull Request SHAs
on:
  push:
  workflow_dispatch:
jobs:
  fetch_all_pull_request_shas:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, mac, windows ]
        include:
          - runtime: linux
            os: ubuntu-latest
          - runtime: mac
            os: macOS-latest
          - runtime: windows
            os: windows-latest
    steps:
    - name: Fetch Pull Request Merge Commits
      shell: bash
      id: fetch_pull_requests
      run: |
        pr_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open&sort=created&direction=desc&per_page=100" \
        | jq -r '.[] | "\(.number) \(.merge_commit_sha)"')
        pr_merge_shas=() # Initialize an empty array
        while read -r pr; do
          pr_number=$(echo $pr | awk '{print $1}')
          pr_merge_sha=$(echo $pr | awk '{print $2}')
          pr_merge_shas+=("$pr_merge_sha") # Append merge SHA to the array
        done <<< "$pr_info"
        merge_shas_string=$(IFS=,; echo "${pr_merge_shas[*]}")
        echo "::set-output name=merge-commits::$merge_shas_string"

  example_matrix:
    runs-on: ${{ matrix.os }}
    needs: fetch_all_pull_request_shas
    strategy:
      matrix:
        merge-commit: ${{ needs.fetch_all_pull_request_shas.outputs.PULL_REQUEST_MERGE_SHAS }}
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout pull request merge commits
        uses: actions/checkout@v3
        with:
          repository: redhat-developer/lsp4ij
          ref: ${{ steps.fetch_pull_requests.outputs.merge-commits }}
