name: Fetch All Open Pull Request SHAs
on:
  push:
  workflow_dispatch:
jobs:
  fetch_all_pull_request_shas:
    runs-on: ubuntu-latest
    outputs:
      merge_shas: ${{ steps.fetch_all_pull_requests.outputs.merge_shas }}
    steps:
    - name: Fetch all opened pull request numbers and merge commit SHAs
      id: fetch_all_pull_requests
      run: |
        pr_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open&sort=created&direction=desc&per_page=100" \
        | jq -r '.[] | "\(.number) \(.merge_commit_sha)"')
        pr_merge_shas=() # Initialize an empty array
        while read -r pr; do
          pr_number=$(echo $pr | awk '{print $1}')
          pr_merge_sha=$(echo $pr | awk '{print $2}')
          echo "PULL_REQUEST_NUMBER=$pr_number" >> $GITHUB_ENV
          echo "PULL_REQUEST_MERGE_SHA=$pr_merge_sha" >> $GITHUB_ENV
          pr_merge_shas+=("$pr_merge_sha") # Append merge SHA to the array
          echo "Pull Request Number: $pr_number"
          echo "Pull Request Merge SHA: $pr_merge_sha"
        done <<< "$pr_info"
        # Convert the array to a JSON array string
        merge_shas_json=$(printf '%s\n' "${pr_merge_shas[@]}" | jq -R . | jq -s .)
        echo "merge-commit: $merge_shas_json"
        # Set the output variable
        echo "::set-output name=merge_shas::$merge_shas_json"

  example_matrix:
    runs-on: ${{ matrix.os }}
    needs: fetch_all_pull_request_shas
    strategy:
      matrix:
        runtime: [ linux, mac, windows ]
        include:
          - runtime: linux
            os: ubuntu-latest
          - runtime: mac
            os: macOS-latest
          - runtime: windows
            os: windows-latest
        matrix: ${{ fromJson(needs.fetch_all_pull_request_shas.outputs.merge_shas) }}
    steps:
      - name: Checkout pull request merge commits
        uses: actions/checkout@v3
        with:
          repository: redhat-developer/lsp4ij
          ref: ${{ matrix }}
