name: Fetch PR Info and Checkout Merge Commits

on:
  push:

jobs:
  fetch_pr_info_and_checkout:
    runs-on: ubuntu-latest
    name: Fetch PR Info and Checkout Merge Commits
    steps:
      - name: 'Fetch all opened pull requests and their merge commit SHAs'
        shell: bash
        id: fetch_all_opened_pull_requests
        run: |
          pr_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" \
          | jq -r '.[] | "\(.number) \(.merge_commit_sha)"')
          
          while read -r line; do
            pr_number=$(echo "$line" | awk '{print $1}')
            pr_merge_sha=$(echo "$line" | awk '{print $2}')
            echo "$pr_number" >> pr_numbers.txt
            echo "$pr_merge_sha" >> pr_merge_shas.txt
          done <<< "$pr_info"
      
          echo "Matrix of Pull Request Numbers:"
          cat pr_numbers.txt
      
          echo "Matrix of Merge Commit SHAs:"
          cat pr_merge_shas.txt
      
      - name: Checkout Merge Commits
        id: checkout_merge_commits
        run: |
          while read -r merge_sha; do
            git checkout $merge_sha
            # Perform any actions related to the specific merge commit here
          done < pr_merge_shas.txt

  # Add other jobs if needed...
