name: Run Dynamic Number of Jobs
on:
  push: 
  workflow_dispatch:
  
jobs:
  generate-job-strategy-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch all opened pull requests (non-draft) and their merge commit SHA'
        shell: bash
        id: fetch_opened_pull_requests
        run: |
          pr_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open&sort=created&direction=desc&per_page=100" \
          | jq -r '.[] | select(.draft == false) | "\(.number) \(.merge_commit_sha)"')
          
          while read -r pr; do
            pr_number=$(echo "$pr" | awk '{print $1}')
            pr_merge_sha=$(echo "$pr" | awk '{print $2}')
            echo "::set-output name=pr_number::$pr_number"
            echo "::set-output name=pr_merge_sha::$pr_merge_sha"
          done <<< "$pr_info"
        env:
          MATRIX_PR_NUMBER: ${{ steps.fetch_opened_pull_requests.outputs.pr_number }}
          MATRIX_PR_MERGE_SHA: ${{ steps.fetch_opened_pull_requests.outputs.pr_merge_sha }}
