name: Fetch PR Merge SHA

on:
  push:

jobs:
  fetch-pr-merge-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch PRs
        id: fetch-prs
        run: |
          TOKEN=$GITHUB_TOKEN
          OWNER=redhat-developer
          REPO=lsp4ij
          PAGE=1
          PER_PAGE=100
          
          PR_LIST=$(curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$OWNER/$REPO/pulls?state=open&per_page=$PER_PAGE&page=$PAGE" | jq -r '.[] | {number: .number, merge_commit_sha: .merge_commit_sha}')

          echo "::set-output name=pr_list::$PR_LIST"

      - name: Output PRs
        run: echo "${{ steps.fetch-prs.outputs.pr_list }}"
